# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6614f1e397e799406edf5bd18ac41b30d9874a1adc532eb67648d808c9a084d3f21601360fff3fac665d978fb3dce403fb2c86e40c53ce7c78b82e33a03b3ffe

test:
  secret_key_base: f6a8a999b2af1d3cd57f033762f14b5948b43e2868f7173d7372c7cc2c8600cb182a17f8b0824756c72ddd9df9f8704d200819529e5ac5636c94d3d8ee5b6018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
